version: "1.0"
diagram:
  pages:
    - id: "page1"
      name: "Test Page - azure-resource-group"
      elements:
        - id: "azure-resource-group-test-id"
          name: "azure-resource-group-test"
          template: "azure-resource-group"
          position:
            x: 100
            y: 100
          parameters:
          resourceGroupName: "rg-production"
          location: "West US 2"
          environment: "Production"
          fillColor: "#E8F5E8"
          strokeColor: "#4CAF50"
