version: 2

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - misspell
  disable:
    - unused
    - gocyclo
    - godot
    - gosec
    - revive
    - unconvert
    - unparam

formatters:
  enable:
    - goimports
    - gofmt

run:
  timeout: 5m
  tests: true
