version: "1.0"
diagram:
  pages:
    - id: "page1"
      name: "Test Page - gcp-region"
      elements:
        - id: "gcp-region-test-id"
          name: "gcp-region-test"
          template: "gcp-region"
          position:
            x: 100
            y: 100
          parameters:
          regionName: "us-west1"
          regionDisplayName: "US West (Oregon)"
          fillColor: "#E8F5E8"
          strokeColor: "#4CAF50"
