version: "1.0"
diagram:
  pages:
    - id: "page1"
      name: "Test Page - azuredevops-environment"
      elements:
        - id: "azuredevops-environment-test-id"
          name: "azuredevops-environment-test"
          template: "azuredevops-environment"
          position:
            x: 100
            y: 100
          parameters:
            environmentName: "TestenvironmentName"
            environmentType: "Production"
            fillColor: "#E0F2F1"
            strokeColor: "#00695C"
