version: "1.0"
diagram:
  pages:
    - id: "page1"
      name: "Test Page - azuredevops-repository"
      elements:
        - id: "azuredevops-repository-test-id"
          name: "azuredevops-repository-test"
          template: "azuredevops-repository"
          position:
            x: 100
            y: 100
          parameters:
            repoName: "Repository"
            repoType: "Git"
            hasPipeline: "false"
            hasServiceConnection: "false"
            description: "Test azuredevops-repository provider"
            fillColor: "#FFFFFF"
            strokeColor: "#DD344C"
