version: "1.0"
metadata:
  title: "Minimal Valid Configuration"
  description: "Minimal configuration that should pass all validation tests"
  author: "Schema Validation"
  created: "2025-08-06T10:00:00Z"

diagram:
  pages:
    - id: "minimal-page"
      name: "Minimal Page"
      elements:
        - type: "shape"
          id: "minimal-shape"
          properties:
            x: 100
            y: 100
            width: 100
            height: 80
            label: "Minimal Shape"
          style:
            fillColor: "#E3F2FD"
            strokeColor: "#1976D2"
