version: "1.0"
metadata:
  title: "Container Element Configuration"
  description: "Standalone container element that can be used independently or as a template input"
  author: "Hippodamus Schema"
  created: "2025-08-06T10:00:00Z"
  tags: ["container", "element", "standalone", "reusable"]

diagram:
  properties:
    grid:
      enabled: true
      size: 10
      color: "#E0E0E0"
    background:
      color: "#FFFFFF"
    scale: 1.0

  pages:
    - id: "container-page"
      name: "Container Element"
      properties:
        width: 600
        height: 400
        background: "#F8F9FA"
      
      elements:
        # Standalone container element with comprehensive configuration
        - type: "container"
          id: "primary-container"
          name: "Primary Container"
          properties:
            x: 50
            y: 50
            width: 500
            height: 300
            label: "Container Element"
            collapsible: true
            collapsed: false
            custom:
              containerType: "layout"
              resizable: true
              scrollable: false
              theme: "modern"
          style:
            # Fill properties
            fillColor: "#F3E5F5"
            fillOpacity: 0.8
            
            # Stroke properties
            strokeColor: "#9C27B0"
            strokeWidth: 2
            strokeOpacity: 1.0
            strokeDashArray: ""
            
            # Typography for container label
            fontFamily: "Roboto"
            fontSize: 16
            fontColor: "#4A148C"
            fontStyle: "bold"
            textAlign: "center"
            verticalAlign: "top"
            labelPosition: "center"
            verticalLabelPosition: "top"
            
            # Container effects
            rounded: true
            shadow: true
            glass: false
            sketch: false
            rotation: 0
            
            # Custom container properties
            custom:
              html: "1"
              whiteSpace: "wrap"
              spacingTop: "25"
              spacingLeft: "15"
              spacingRight: "15"
              spacingBottom: "15"
          tags: ["primary", "container", "reusable"]
          nesting:
            mode: "child"
            autoResize: false
            spacing: 15
            arrangement: "vertical"
            padding:
              top: 35
              right: 20
              bottom: 20
              left: 20
            childDefaults:
              style:
                fillColor: "#FCE4EC"
                strokeColor: "#E91E63"
                strokeWidth: 1
                rounded: true
                fontSize: 12
          children:
            # Container child elements
            - type: "shape"
              id: "container-item-1"
              name: "Container Item 1"
              properties:
                x: 0
                y: 0
                width: 460
                height: 50
                label: "Header Section"
                shape: "rectangle"
              style:
                fillColor: "#E1BEE7"
                strokeColor: "#8E24AA"
                strokeWidth: 1
                fontSize: 14
                fontStyle: "bold"
                textAlign: "center"
                verticalAlign: "middle"

            - type: "shape"
              id: "container-item-2"
              name: "Container Item 2"
              properties:
                x: 0
                y: 65
                width: 220
                height: 80
                label: "Content Left"
                shape: "rectangle"
              style:
                fillColor: "#F8BBD9"
                strokeColor: "#C2185B"
                strokeWidth: 1
                fontSize: 12
                textAlign: "center"
                verticalAlign: "middle"

            - type: "shape"
              id: "container-item-3"
              name: "Container Item 3"
              properties:
                x: 240
                y: 65
                width: 220
                height: 80
                label: "Content Right"
                shape: "rectangle"
              style:
                fillColor: "#F8BBD9"
                strokeColor: "#C2185B"
                strokeWidth: 1
                fontSize: 12
                textAlign: "center"
                verticalAlign: "middle"

            - type: "shape"
              id: "container-item-4"
              name: "Container Item 4"
              properties:
                x: 0
                y: 160
                width: 460
                height: 40
                label: "Footer Section"
                shape: "rectangle"
              style:
                fillColor: "#E1BEE7"
                strokeColor: "#8E24AA"
                strokeWidth: 1
                fontSize: 11
                textAlign: "center"
                verticalAlign: "middle"
