name: "kubernetes-pod"
description: "Kubernetes Pod"
version: "1.0"

dependencies:
  - name: "namespace"
    type: "kubernetes-namespace"
    required: true
    relationship: "parent"
    description: "Parent Kubernetes namespace"

parameters:
  - name: "podName"
    type: "string"
    default: "pod"
    description: "Pod name"
  - name: "image"
    type: "string"
    default: "nginx:latest"
    description: "Container image"
  - name: "replicas"
    type: "number"
    default: 1
    description: "Number of replicas"
  - name: "fillColor"
    type: "color"
    default: "#FFF3E0"
    description: "Background color"
  - name: "strokeColor"
    type: "color"
    default: "#F57C00"
    description: "Border color"

elements:
  - type: "shape"
    properties:
      width: 120
      height: 80
      label: "{{.podName}}"
      shape: "rectangle"
      custom:
        image: "{{.image}}"
        replicas: "{{.replicas}}"
    style:
      fillColor: "{{.fillColor}}"
      strokeColor: "{{.strokeColor}}"
      strokeWidth: 2.0
      fontFamily: "Segoe UI"
      fontSize: 12
      fontColor: "#000000"
      fontStyle: "bold"
      textAlign: "center"
      verticalAlign: "middle"
      rounded: true
      shadow: true
