name: "kubernetes-namespace"
description: "Kubernetes Namespace container"
version: "1.0"

dependencies:
  - name: "cluster"
    type: "kubernetes-cluster"
    required: true
    relationship: "parent"
    description: "Parent Kubernetes cluster"

parameters:
  - name: "namespaceName"
    type: "string"
    default: "default"
    description: "Namespace name"
  - name: "environment"
    type: "string"
    default: "development"
    description: "Environment (development, staging, production)"
  - name: "fillColor"
    type: "color"
    default: "#F1F8E9"
    description: "Background color"
  - name: "strokeColor"
    type: "color"
    default: "#689F38"
    description: "Border color"

elements:
  - type: "container"
    properties:
      width: 700
      height: 400
      label: "{{.namespaceName}}"
      custom:
        environment: "{{.environment}}"
    style:
      fillColor: "{{.fillColor}}"
      strokeColor: "{{.strokeColor}}"
      strokeWidth: 2.0
      fontFamily: "Segoe UI"
      fontSize: 14
      fontColor: "#000000"
      fontStyle: "bold"
      textAlign: "center"
      verticalAlign: "top"
      rounded: true
      shadow: true
    nesting:
      mode: "container"
      autoResize: true
      padding:
        top: 40
        right: 20
        bottom: 20
        left: 20
      spacing: 30
      arrangement: "horizontal"
