name: "azure-environment"
description: "Azure DevOps Environment"
version: "1.0"

dependencies:
  - name: "custom"
    type: "container" #container or group, defaults to container
    required: false
    relationship: "parent"
    description: "Custom parent object"

parameters:
  - name: "environmentName"
    type: "string"
    required: true
    description: "Environment name"
  - name: "environmentType"
    type: "string"
    default: "Production"
    description: "Environment type (Development, Staging, Production)"
  - name: "fillColor"
    type: "color"
    default: "#E0F2F1"
    description: "Background color"
  - name: "strokeColor"
    type: "color"
    default: "#00695C"
    description: "Border color"

group:
  properties:
    width: 140
    height: 60
    label: "🌍 {{.environmentName}}"
    shape: "rounded=1;whiteSpace=wrap;html=1;"
  style:
    fillColor: "{{.fillColor}}"
    strokeColor: "{{.strokeColor}}"
    strokeWidth: 2
    fontFamily: "Segoe UI"
    fontSize: 11
    fontColor: "#004D40"
    textAlign: "center"
    rounded: true
  autoResize: false
  arrangement: "free"
