version: "1.0"
diagram:
  pages:
    - id: "service-connection"
      name: "azuredevops-service-connection"
      elements:
        - id: "azuredevops-service-connection-test-id"
          name: "azuredevops-service-connection-test"
          template: "azuredevops-service-connection"
          position:
            x: 100
            y: 100
          parameters:
            connectionName: "TestconnectionName"
            connectionType: "Azure Resource Manager"
            fillColor: "#FCE4EC"
            strokeColor: "#C2185B"
