version: "1.0"
diagram:
  pages:
    - id: "project"
      name: "azuredevops-project"
      elements:
        - id: "azuredevops-project-test-id"
          name: "azuredevops-project-test"
          template: "azuredevops-project"
          position:
            x: 100
            y: 100
          parameters:
            projectName: "Project"
            projectType: "Agile"
            iconShape: "img/lib/azure2/devops/Azure_DevOps.svg"
            fillColor: "#F1F8E9"
            strokeColor: "#759C3E"
