version: "1.0"
metadata:
  title: "Edge Case Tests"
  description: "Tests for edge cases and boundary conditions"
  author: "Schema Validation"

diagram:
  pages:
    # Very large page
    - id: "large-page"
      name: "Large Page Test"
      properties:
        width: 10000
        height: 10000
      elements:
        # Element at extreme coordinates
        - type: "shape"
          id: "extreme-coords"
          properties:
            x: 9999.99
            y: 9999.99
            width: 0.01
            height: 0.01
            label: "Extreme Coordinates"

        # Zero-sized element
        - type: "shape"
          id: "zero-size"
          properties:
            x: 100
            y: 100
            width: 0
            height: 0
            label: "Zero Size"

        # Negative coordinates
        - type: "shape"
          id: "negative-coords"
          properties:
            x: -100
            y: -50
            width: 50
            height: 30
            label: "Negative Coords"

        # Very high Z-index
        - type: "shape"
          id: "high-z"
          properties:
            x: 200
            y: 200
            width: 100
            height: 80
            z: 999999
            label: "High Z-Index"

    # Empty page
    - id: "empty-page"
      name: "Empty Page"
      elements: []

    # Page with maximum nesting depth
    - id: "deep-nesting-page"
      name: "Deep Nesting Test"
      elements:
        - type: "container"
          id: "level-1"
          properties:
            x: 50
            y: 50
            width: 500
            height: 400
            label: "Level 1"
          nesting:
            mode: "child"
          children:
            - type: "container"
              id: "level-2"
              properties:
                x: 25
                y: 25
                width: 450
                height: 350
                label: "Level 2"
              nesting:
                mode: "child"
              children:
                - type: "container"
                  id: "level-3"
                  properties:
                    x: 25
                    y: 25
                    width: 400
                    height: 300
                    label: "Level 3"
                  nesting:
                    mode: "child"
                  children:
                    - type: "shape"
                      id: "deep-nested-shape"
                      properties:
                        x: 50
                        y: 50
                        width: 100
                        height: 80
                        label: "Deep Nested"
