version: "1.0"
diagram:
  pages:
    - id: "page1"
      name: "Test Page - gcp-gke-cluster"
      elements:
        - id: "gcp-gke-cluster-test-id"
          name: "gcp-gke-cluster-test"
          template: "gcp-gke-cluster"
          position:
            x: 100
            y: 100
          parameters:
          clusterName: "gke-cluster"
          version: "1.28"
          nodePoolName: "default-pool"
          machineType: "e2-standard-4"
          nodeCount: "3
    description: "
          fillColor: "#E3F2FD"
          strokeColor: "#1976D2"
