version: "1.0"
metadata:
  title: "AWS Kubernetes Deployment"
  description: "Complete AWS infrastructure with EKS cluster and applications"

variables:
  companyName: "TechCorp"
  environment: "production"

diagram:
  pages:
    - id: "main"
      name: "AWS Kubernetes Infrastructure"
      elements:
        # AWS Infrastructure Hierarchy
        - id: "aws-org"
          name: "aws-org"
          type: "template"
          template: "aws-organization"
          parameters:
            organizationName: "{{.companyName}} AWS Organization"
            
        - id: "prod-account"
          name: "prod-account"
          type: "template"
          template: "aws-account"
          parameters:
            accountName: "{{.environment | title}}"
            accountId: "111222333444"
          dependencies:
            - "aws-org"
            
        - id: "us-west-region"
          name: "us-west-region"
          type: "template"
          template: "aws-region"
          parameters:
            regionName: "us-west-2"
          dependencies:
            - "prod-account"
            
        - id: "eks-cluster"
          name: "eks-cluster"
          type: "template"
          template: "aws-eks-cluster"
          parameters:
            clusterName: "{{.environment}}-cluster"
            version: "1.28"
            nodePoolName: "worker-nodes"
            instanceType: "m5.large"
            nodeCount: 5
          dependencies:
            - "us-west-region"

        # Kubernetes Applications
        - id: "ingress-controller"
          name: "ingress-controller"
          type: "template"
          template: "kubernetes-deployment"
          parameters:
            deploymentName: "nginx-ingress"
            replicas: 2
            clusterType: "eks"
          dependencies:
            - "eks-cluster"
            
        - id: "web-app"
          name: "web-app"
          type: "template"
          template: "kubernetes-deployment"
          parameters:
            deploymentName: "web-application"
            replicas: 3
            clusterType: "eks"
          dependencies:
            - "eks-cluster"
            
        - id: "api-service"
          name: "api-service"
          type: "template"
          template: "kubernetes-service"
          parameters:
            serviceName: "api-service"
            serviceType: "ClusterIP"
            clusterType: "eks"
          dependencies:
            - "eks-cluster"
            
        - id: "database"
          name: "database"
          type: "template"
          template: "kubernetes-deployment"
          parameters:
            deploymentName: "postgres-db"
            replicas: 1
            clusterType: "eks"
          dependencies:
            - "eks-cluster"
            
        - id: "redis-cache"
          name: "redis-cache"
          type: "template"
          template: "kubernetes-deployment"
          parameters:
            deploymentName: "redis-cache"
            replicas: 2
            clusterType: "eks"
          dependencies:
            - "eks-cluster"
