version: "1.0"
diagram:
  pages:
    - id: "page1"
      name: "Test Page - azure-management-group"
      elements:
        - id: "azure-management-group-test-id"
          name: "azure-management-group-test"
          template: "azure-management-group"
          position:
            x: 100
            y: 100
          parameters:
          managementGroupName: "Production MG"
          managementGroupId: "prod-mg-001"
          displayName: "Production Management Group"
          fillColor: "#E8F5E8"
          strokeColor: "#4CAF50"
